/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as DefinirMotDePasseRouteImport } from './routes/definir-mot-de-passe'
import { Route as FormulaireRouteImport } from './routes/formulaire'
import { Route as GlossaireRouteImport } from './routes/glossaire'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as SecurisationRouteImport } from './routes/securisation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirMotDePasseRoute = DefinirMotDePasseRouteImport.update({
  id: '/definir-mot-de-passe',
  path: '/definir-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulaireRoute = FormulaireRouteImport.update({
  id: '/formulaire',
  path: '/formulaire',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaireRoute = GlossaireRouteImport.update({
  id: '/glossaire',
  path: '/glossaire',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurisationRoute = SecurisationRouteImport.update({
  id: '/securisation',
  path: '/securisation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connexion': typeof ConnexionRoute
  '/definir-mot-de-passe': typeof DefinirMotDePasseRoute
  '/formulaire': typeof FormulaireRoute
  '/glossaire': typeof GlossaireRoute
  '/guide': typeof GuideRoute
  '/prompts': typeof PromptsRoute
  '/securisation': typeof SecurisationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connexion': typeof ConnexionRoute
  '/definir-mot-de-passe': typeof DefinirMotDePasseRoute
  '/formulaire': typeof FormulaireRoute
  '/glossaire': typeof GlossaireRoute
  '/guide': typeof GuideRoute
  '/prompts': typeof PromptsRoute
  '/securisation': typeof SecurisationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connexion': typeof ConnexionRoute
  '/definir-mot-de-passe': typeof DefinirMotDePasseRoute
  '/formulaire': typeof FormulaireRoute
  '/glossaire': typeof GlossaireRoute
  '/guide': typeof GuideRoute
  '/prompts': typeof PromptsRoute
  '/securisation': typeof SecurisationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connexion'
    | '/definir-mot-de-passe'
    | '/formulaire'
    | '/glossaire'
    | '/guide'
    | '/prompts'
    | '/securisation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/connexion'
    | '/definir-mot-de-passe'
    | '/formulaire'
    | '/glossaire'
    | '/guide'
    | '/prompts'
    | '/securisation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/connexion'
    | '/definir-mot-de-passe'
    | '/formulaire'
    | '/glossaire'
    | '/guide'
    | '/prompts'
    | '/securisation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConnexionRoute: typeof ConnexionRoute
  DefinirMotDePasseRoute: typeof DefinirMotDePasseRoute
  FormulaireRoute: typeof FormulaireRoute
  GlossaireRoute: typeof GlossaireRoute
  GuideRoute: typeof GuideRoute
  PromptsRoute: typeof PromptsRoute
  SecurisationRoute: typeof SecurisationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-mot-de-passe': {
      id: '/definir-mot-de-passe'
      path: '/definir-mot-de-passe'
      fullPath: '/definir-mot-de-passe'
      preLoaderRoute: typeof DefinirMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaire': {
      id: '/formulaire'
      path: '/formulaire'
      fullPath: '/formulaire'
      preLoaderRoute: typeof FormulaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossaire': {
      id: '/glossaire'
      path: '/glossaire'
      fullPath: '/glossaire'
      preLoaderRoute: typeof GlossaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securisation': {
      id: '/securisation'
      path: '/securisation'
      fullPath: '/securisation'
      preLoaderRoute: typeof SecurisationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConnexionRoute: ConnexionRoute,
  DefinirMotDePasseRoute: DefinirMotDePasseRoute,
  FormulaireRoute: FormulaireRoute,
  GlossaireRoute: GlossaireRoute,
  GuideRoute: GuideRoute,
  PromptsRoute: PromptsRoute,
  SecurisationRoute: SecurisationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
